---
language: node_js
node_js: "8.10"
cache: npm

# only run on hotfix/release/master/develop and feature/* branches
# to stick to the git flow process
# and allow a github pages site in case it gets added
branches:
  only:
    - master
    - develop
    - hotfix/.*
    - release/.*
    - feature/.*
    - gh-pages

stages:
  - unit tests
  - build
  - name: test deploy
    if: branch = master
  - name: test test deploy
    if: branch = master

script:
  - npm install -g serverless
jobs:
  include:
    - stage: unit tests
      name: "Unit Tests"
      script: npm run test:unittest
    - name: "Test Schemas Hints"
      script: npm run test:schemahints
    - name: "Test Schemas"
      script: npm run test:schemas
    - name: "Serverless Tests"
      script: npm run test:serverless
    - name: "Code coverage check"
      script: npm run coverage

    - stage: build
      script: sls package

    - stage: test deploy
      script: sls deploy --stage testing --package .serverless

    - stage: test test deploy
      name: "Test Fibonacci function"
      script: sls invoke -f fibonacci -s testing -d "$(cat slstest/fibonacci.event.json)"
